# Generated by Django 5.2.7 on 2025-11-01 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coord_x",
                    models.IntegerField(
                        default=0, help_text="X coordinate on map (0 = center)"
                    ),
                ),
                (
                    "coord_y",
                    models.IntegerField(
                        default=0, help_text="Y coordinate on map (0 = center)"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True,
                        help_text="User-assigned location number",
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Name of the location", max_length=200
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Location picture",
                        null=True,
                        upload_to="locations/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes about this location"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["coord_y", "coord_x"],
                "unique_together": {("coord_x", "coord_y")},
            },
        ),
    ]
