# Generated by Django 5.2.7 on 2025-11-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="notes",
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Note content")),
                (
                    "author",
                    models.CharField(
                        default="Anonymous", help_text="Note author", max_length=100
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Is this task completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_set",
                        to="home.location",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
