# Generated by Django 5.2.7 on 2025-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_location_notes_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Journal note content")),
                (
                    "author",
                    models.CharField(
                        default="Anonymous", help_text="Note author", max_length=100
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Is this task completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"]},
        ),
    ]
