# Generated by Django 5.2.7 on 2025-11-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_journalnote_alter_note_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_id",
                    models.CharField(
                        help_text="Unique edge ID for React Flow", max_length=100
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Source node ID", max_length=100),
                ),
                (
                    "target",
                    models.CharField(help_text="Target node ID", max_length=100),
                ),
                ("text", models.TextField(blank=True, help_text="Edge label text")),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Is this edge completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_edges",
                        to="home.location",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("location", "edge_id")},
            },
        ),
        migrations.CreateModel(
            name="DecisionNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="Unique node ID for React Flow", max_length=100
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        default="outcomeNode",
                        help_text="Type of node (outcomeNode)",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True, help_text="Node text content")),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Is this node completed?"
                    ),
                ),
                ("position_x", models.FloatField(help_text="X position in the canvas")),
                ("position_y", models.FloatField(help_text="Y position in the canvas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_nodes",
                        to="home.location",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("location", "node_id")},
            },
        ),
    ]
