# Generated by Django 5.2.7 on 2025-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_decisionedge_decisionnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="assigned_edge_id",
            field=models.CharField(
                blank=True,
                help_text="Edge ID this note is assigned to as a requirement",
                max_length=100,
                null=True,
            ),
        ),
    ]
