# Generated by Django 5.2.7 on 2025-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_note_assigned_edge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionnode",
            name="cost",
            field=models.TextField(
                blank=True, help_text="Cost or resource requirement"
            ),
        ),
    ]
